# autogenerated
# overrideable vars used in implicit make rules
TARGET_ARCH ?= -march=native
CFLAGS ?= -Os
CPPFLAGS += -Wall -Wextra -Wshadow
LDFLAGS += ${CFLAGS}

# list of targets to build, generated from .c files containing a main() function:

TARGETS=qrpn

all : ${TARGETS}

# for each target, the list of objects to link, generated by recursively crawling include statements with a corresponding .c file:

qrpn : qrpn.o

# for each object, the list of headers it depends on, generated by recursively crawling include statements:

qrpn.o : qrpn.h

*.o : Makefile

clean :
	$(RM) -rf *.o *.dSYM ${TARGETS}
.PHONY: clean all
